# Generated by Django 5.1 on 2024-08-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_pricing", "0004_data_migration_add_default_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="label",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
